name = "batdigest-email"
main = "src/index.ts"
compatibility_date = "2024-08-20"
account_id = "f791be9be6d12e1353b13e587d3eccd9"

[vars]
ALLOWED_ORIGINS = "https://swing-analysis-api.brianduryea.workers.dev,http://localhost:8787,http://localhost:5004,https://batdigest-email.brianduryea.workers.dev"